### PR TITLE
Deprecate attachment upload by file path

### LINKED ISSUE #264: Uploads: is_file(): File name is longer than the maximum allowed path length on this platform (4096)
When I try to upload binary files, I get the message:

```
yii\base\ErrorException: is_file(): File name is longer than the maximum allowed path length on this platform (4096): MZ����@���	�!�L�!This program cannot be run in DOS mode.

$�1��P���P���P��*_���P���P��OP��*_���P�ҽs���P��.V���P��Rich�P��PEL1�MX�b*�2�@���U@��� h�@hU`5��.text�`b `.rdata��f@@.data��z@�.ndatap���.rsrch� ��@@U���\�}t+�}F�Eu
.......
```

Stack:
```
Stack trace:
#0 /var/www/dev.fopro-plus.jki.intern/robin/vendor/kbsali/redmine-api/src/Redmine/Client.php(670): yii\web\ErrorHandler->handleError('2', ''is_file(): Fil...', ''/var/www/dev.f...', '670', '['path' => '/up...')
#1 /var/www/dev.fopro-plus.jki.intern/robin/vendor/kbsali/redmine-api/src/Redmine/Client.php(670): ::is_file(''MZ\x90\\003\\004\xFF\xFF\xB8...')
#2 /var/www/dev.fopro-plus.jki.intern/robin/vendor/kbsali/redmine-api/src/Redmine/Client.php(641): Redmine\Client->isUploadCall(''/uploads.json?...', ''MZ\x90\\000\\003\\00...')
#3 /var/www/dev.fopro-plus.jki.intern/robin/vendor/kbsali/redmine-api/src/Redmine/Client.php(754): Redmine\Client->prepareRequest(''/uploads.json?...', ''POST'', ''MZ\x90\\000\\003\\00...')
#4 /var/www/dev.fopro-plus.jki.intern/robin/vendor/kbsali/redmine-api/src/Redmine/Client.php(306): Redmine\Client->runRequest(''/uploads.json?...', ''POST'', ''MZ\x90\\000\\003\\00...')
#5 /var/www/dev.fopro-plus.jki.intern/robin/vendor/kbsali/redmine-api/src/Redmine/Client.php(200): Redmine\Client->post(''/uploads.json?...', ''MZ\x90\\000\\003\\00...')
#6 /var/www/dev.fopro-plus.jki.intern/robin/vendor/kbsali/redmine-api/src/Redmine/Api/AbstractApi.php(79): Redmine\Client->requestPost(''/uploads.json?...', ''MZ\x90\\000\\003\\00...')
#7 /var/www/dev.fopro-plus.jki.intern/robin/vendor/kbsali/redmine-api/src/Redmine/Api/Attachment.php(54): Redmine\Api\Attachment->post(''/uploads.json?...', ''MZ\x90\\000\\003\\00...')
#8 /var/www/dev.fopro-plus.jki.intern/robin/vendor/jki/yii2-proma/controllers/PromaController.php(70): Redmine\Api\Attachment->upload(''MZ\x90\\000\\003\\00...', '???')
```

is_file seems to not be liking the raw content??

Any ideas?

Using: v1.7.0

### PR DESCRIPTION
**Pull request by Art4**
Uploading an attachment could be made by `$client->getApi('attachment')->upload('file content');` as documented in the docs: https://github.com/kbsali/php-redmine-api/blob/v2.0.1/docs/usage.md

However in #222 a new way of uploading files via filepath was introduced as a "fix". This way has led to a number of problems like #235 and #264. 

This method can additionally lead to a potential security problem: Assume someone wants to upload the file `file.txt`, but the file contains the path to another file:

**file.txt**

```
/etc/passwd
```

If one now runs `$client->getApi('attachment')->upload(file_get_contents('./file.txt'));` the library will check with `is_file()` for the existence of the `/etc/passwd` file and will upload this file instead.

As a solution I would recommend to deprecate the attachment upload by filename and remove it in the next major version.

This PR will fix #264.

@kbsali Depending on how critical this issue is rated, I would also release version 3.0 very soon.

### CODE REVIEW

File: src/Redmine/Client/ClientApiTrait.php [hunk 1]
```diff
@@ -53,4 +53,21 @@ public function getApi(string $name): Api
 
         return $this->apiInstances[$name];
     }
+
+    private function isUploadCall(string $path): bool
+    {
+        $path = strtolower($path);
+
+        return (false !== strpos($path, '/uploads.json')) or (false !== strpos($path, '/uploads.xml'));
```
Comment (kbsali) [inline src/Redmine/Client/ClientApiTrait.php]:
```suggestion
        return (false !== strpos($path, '/uploads.json')) || (false !== strpos($path, '/uploads.xml'));
```

File: src/Redmine/Client/ClientApiTrait.php [hunk 2]
```diff
@@ -53,4 +53,21 @@ public function getApi(string $name): Api
...
+    }
+
+    private function isUploadCallAndFilepath(string $path, string $body): bool
```
Comment (kbsali) [inline src/Redmine/Client/ClientApiTrait.php]: The name of the method is not very clear to me. What do you mean with "AndFilePath"?

File: src/Redmine/Client/NativeCurlClient.php [hunk 3]
```diff
@@ -271,7 +271,9 @@ private function createCurl(string $method, string $path, string $body = '')
         switch ($method) {
             case 'post':
                 $curlOptions[CURLOPT_POST] = 1;
-                if ($this->isUploadCall($path, $body)) {
+                if ($this->isUploadCallAndFilepath($path, $body)) {
+                    @trigger_error('Upload an attachment by filepath is deprecated, use file_get_contents() to upload the file content instead.', E_USER_DEPRECATED);
```
Comment (kbsali) [inline src/Redmine/Client/NativeCurlClient.php]:
```suggestion
                    @trigger_error('Uploading an attachment by filepath is deprecated, use file_get_contents() to upload the file content instead.', E_USER_DEPRECATED);
```

File: src/Redmine/Client/Psr18Client.php [hunk 4]
```diff
@@ -181,7 +181,9 @@ private function createRequest(string $method, string $path, string $body = ''):
 
         switch ($method) {
             case 'POST':
-                if ($this->isUploadCall($path, $body)) {
+                if ($this->isUploadCallAndFilepath($path, $body)) {
+                    @trigger_error('Upload an attachment by filepath is deprecated, use file_get_contents() to upload the file content instead.', E_USER_DEPRECATED);
```
Comment (kbsali) [inline src/Redmine/Client/Psr18Client.php]:
```suggestion
                    @trigger_error('Uploading an attachment by filepath is deprecated, use file_get_contents() to upload the file content instead.', E_USER_DEPRECATED);
```

**Review by kbsali — COMMENTED** [review]
nice one! :ok_hand:

File: src/Redmine/Client/ClientApiTrait.php (hunk 2 above)
Comment (Art4) [reply src/Redmine/Client/ClientApiTrait.php]: The method checks if `$path` is an upload call and if `$body` contains a valid file path using `is_file()`, but was previously named `isUploadCall()` which does not fully describe the function. I extracted the upload check into its own method (named `isUploadCall()`) and now I needed a name that better described the meaning of the previous method. That is the reason why I came up with `isUploadCallAndFilepath()`.

Comment (Art4) [reply src/Redmine/Client/ClientApiTrait.php]: Maybe we should remove the `isUploadCall()` from this method and rename `isUploadCallAndFilepath()` to `isFilepath()`?

Comment (kbsali) [reply src/Redmine/Client/ClientApiTrait.php]: `isValidFilePath` ?
`isAuthorizedFilePath` ?

**Comment by kbsali** [comment]
> @kbsali Depending on how critical this issue is rated, I would also release version 3.0 very soon.

oh? why not a `minor` version update?

File: src/Redmine/Client/ClientApiTrait.php (hunk 2 above)
Comment (Art4) [reply src/Redmine/Client/ClientApiTrait.php]: I will remove the call of `isUploadCall()` and rename it to `isValidFilePath()`.

**Comment by Art4** [comment]
> oh? why not a `minor` version update?

Removing this functionality is a breaking change and requires a major version.

File: src/Redmine/Client/ClientApiTrait.php (hunk 2 above)
Comment (Art4) [reply src/Redmine/Client/ClientApiTrait.php]: Done.

**Review by kbsali — COMMENTED** [review]
:+1:

**Review by kbsali — APPROVED** [review]
