### PR TITLE
Return `false` from `AbstractApi::get()` on empty response body

### LINKED ISSUE #274: Changes made in #257 introduces a BC break
Changes made in [#257](https://github.com/kbsali/php-redmine-api/pull/257/files#diff-a0d92f5dcb3b7fa15b6523c906ed0ad089ba350c1aa9d6cb36a011143fd246c8R66) introduces a BC break in the return value of [`AbstractApi::get()`](https://github.com/kbsali/php-redmine-api/pull/257/files#diff-a0d92f5dcb3b7fa15b6523c906ed0ad089ba350c1aa9d6cb36a011143fd246c8R47).
Prior to these changes, if the response body was empty, `get()` was returning `false`, and currently it returns `null`.
Since this package lacks a exception oriented flow in front of HTTP responses ending in error codes (400~599), my implementation relies in the return values to determine the situation about a request.

Obviously the compatibility with PSR-18 is great, I'd just like to expose this situation in order to verify if these changes could respect BC.
Note that this is the only one BC break I've checked, since this is the first issue I encountered after updating the dependency.

### PR DESCRIPTION
**Pull request by phansys**
Fixes #274.

### CODE REVIEW

**Comment by kbsali** [comment]
the CI is broken, could you try to fix it?

File: src/Redmine/Api/AbstractApi.php [hunk 1]
```diff
@@ -42,7 +42,7 @@ public function lastCallFailed()
      * @param string $path
      * @param bool   $decodeIfJson
      *
-     * @return string|array|SimpleXMLElement|null
+     * @return string|array|SimpleXMLElement|false|null
```
Comment (Art4) [inline src/Redmine/Api/AbstractApi.php]: Please remove the `|null` because this will never be the case.

File: tests/Unit/Api/AbstractApiTest.php [hunk 2]
```diff
@@ -129,7 +129,8 @@ public function getJsonDecodingFromGetMethodData()
             ['{"foo_bar": 12345}', null, ['foo_bar' => 12345]], // test decode by default
             ['{"foo_bar": 12345}', false, '{"foo_bar": 12345}'],
             ['{"foo_bar": 12345}', true, ['foo_bar' => 12345]],
-            ['', true, null], // test decode with empty body
+            'Empty body, JSON decode: false' => ['', false, false],
```
Comment (Art4) [inline tests/Unit/Api/AbstractApiTest.php:132]: Instead of having the comment in the key please move it at the end of the line like 
`['', false, false], // Empty body, JSON decode: false`

File: tests/Unit/Api/AbstractApiTest.php [hunk 3]
```diff
@@ -129,7 +129,8 @@ public function getJsonDecodingFromGetMethodData()
...
+            'Empty body, JSON decode: true' => ['', true, false],
```
Comment (Art4) [inline tests/Unit/Api/AbstractApiTest.php:133]: Same here. See comment above.

**Review by Art4 — CHANGES_REQUESTED** [review]
This PR will fix the BC break. Thank you :+1: 

To fix the tests we also have to fix the expected return type in IssueRelation.php, see
https://github.com/kbsali/php-redmine-api/blob/v1.8.0/src/Redmine/Api/IssueRelation.php#L45

```diff
-        if (null === $ret) {
+        if (false === $ret) {
```

Also please see the requested changes.

File: tests/Unit/Api/AbstractApiTest.php (hunk 2 above)
Comment (phansys) [reply tests/Unit/Api/AbstractApiTest.php:132]: This makes the test suite less explicit about the failed case, but no problem. I'll place the context information as comment.

**Comment by phansys** [comment]
>To fix the tests we also have to fix the expected return type in IssueRelation.php, see

I saw that condition, that's in part why I couldn't spend more time in this PR yet.
Given that condition was introduced in version [`0.3.0`](
https://github.com/kbsali/php-redmine-api/commit/f3373fafde26e587216b20ab9dfe27012a2d1938#diff-b1f8fa84ea4346bf139e9bcbbf532b028e200f7e3aeea61d81ada0bcd3ce7193R39), I don't know if it was always the expected value near the failed responses.
I need to analyze how it was behaving prior to #257 in order to understand how it was working.
Even, since the changes in #257 were published in version [`1.7.0`](https://github.com/kbsali/php-redmine-api/compare/v1.6.0...v1.7.0), I wonder if we should provide a BC layer with a deprecation path for users who can be relying on this new behavior. Have you some concerns about this?

File: tests/Unit/Api/AbstractApiTest.php (hunk 2 above)
Comment (Art4) [reply tests/Unit/Api/AbstractApiTest.php:132]: Wow, I didn't know that phpunit will use the key for the description in a failing test. :exploding_head: 
Please keep it as it is. :+1:

**Comment by Art4** [comment]
To be honest I have not deeply dived into the AbstractApi.php. With #257 I moved the parsing functionality from `Client::get()` to `AbstractApi::get()` and made the mistake to return `null` instead of `false`. I would keep it this old way returning `false` for BC instead of provide a deprecation path. Rewriting the AbstractApi could be a task after releasing v2.

File: src/Redmine/Api/AbstractApi.php (hunk 1 above)
Comment (phansys) [reply src/Redmine/Api/AbstractApi.php]: `json_decode()` is able to return `null` if the decoded string is "null", but I think the API response will never print that.
Ref: https://3v4l.org/8sXS6.

**Review by phansys — COMMENTED** [review]
Should I update the CHANGELOG explaining this change or it is updated when releasing?

**Review by Art4 — APPROVED** [review]
@phansys Thank you very much. :+1: 
@kbsali This PR is ready for merge. After merge I will release v1.8.1 and port this PR into v2 branch.

**Comment by Art4** [comment]
> Should I update the CHANGELOG explaining this change or it is updated when releasing?

I will do it before releasing v1.8.1. Thank you.

**Comment by kbsali** [comment]
Thanks @phansys ! 👍

**Comment by Art4** [comment]
@kbsali Can you please merge this? Or can I do it?

**Comment by kbsali** [comment]
sure, go ahead! :)
